// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_def/login.proto

package com.luv.face2face.protobuf.generate.ser2cli.login;

public final class Server {
  private Server() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResServerLoginSuccOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string description = 1;
    /**
     * <code>required string description = 1;</code>
     */
    boolean hasDescription();
    /**
     * <code>required string description = 1;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>required string description = 1;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code ResServerLoginSucc}
   *
   * <pre>
   *服务器登录成功响应
   * </pre>
   */
  public static final class ResServerLoginSucc extends
      com.google.protobuf.GeneratedMessage
      implements ResServerLoginSuccOrBuilder {
    // Use ResServerLoginSucc.newBuilder() to construct.
    private ResServerLoginSucc(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResServerLoginSucc(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResServerLoginSucc defaultInstance;
    public static ResServerLoginSucc getDefaultInstance() {
      return defaultInstance;
    }

    public ResServerLoginSucc getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResServerLoginSucc(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              description_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.luv.face2face.protobuf.generate.ser2cli.login.Server.internal_static_ResServerLoginSucc_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.luv.face2face.protobuf.generate.ser2cli.login.Server.internal_static_ResServerLoginSucc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc.class, com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc.Builder.class);
    }

    public static com.google.protobuf.Parser<ResServerLoginSucc> PARSER =
        new com.google.protobuf.AbstractParser<ResServerLoginSucc>() {
      public ResServerLoginSucc parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResServerLoginSucc(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResServerLoginSucc> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string description = 1;
    public static final int DESCRIPTION_FIELD_NUMBER = 1;
    private java.lang.Object description_;
    /**
     * <code>required string description = 1;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string description = 1;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string description = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      description_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDescription()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDescriptionBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDescriptionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResServerLoginSucc}
     *
     * <pre>
     *服务器登录成功响应
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSuccOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.luv.face2face.protobuf.generate.ser2cli.login.Server.internal_static_ResServerLoginSucc_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.luv.face2face.protobuf.generate.ser2cli.login.Server.internal_static_ResServerLoginSucc_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc.class, com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc.Builder.class);
      }

      // Construct using com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.luv.face2face.protobuf.generate.ser2cli.login.Server.internal_static_ResServerLoginSucc_descriptor;
      }

      public com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc getDefaultInstanceForType() {
        return com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc.getDefaultInstance();
      }

      public com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc build() {
        com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc buildPartial() {
        com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc result = new com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.description_ = description_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc) {
          return mergeFrom((com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc other) {
        if (other == com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc.getDefaultInstance()) return this;
        if (other.hasDescription()) {
          bitField0_ |= 0x00000001;
          description_ = other.description_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDescription()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginSucc) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string description = 1;
      private java.lang.Object description_ = "";
      /**
       * <code>required string description = 1;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string description = 1;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string description = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string description = 1;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string description = 1;</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000001);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>required string description = 1;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        description_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ResServerLoginSucc)
    }

    static {
      defaultInstance = new ResServerLoginSucc(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ResServerLoginSucc)
  }

  public interface ResServerLoginFailedOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string description = 1;
    /**
     * <code>required string description = 1;</code>
     */
    boolean hasDescription();
    /**
     * <code>required string description = 1;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>required string description = 1;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code ResServerLoginFailed}
   *
   * <pre>
   *服务器登录失败响应
   * </pre>
   */
  public static final class ResServerLoginFailed extends
      com.google.protobuf.GeneratedMessage
      implements ResServerLoginFailedOrBuilder {
    // Use ResServerLoginFailed.newBuilder() to construct.
    private ResServerLoginFailed(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResServerLoginFailed(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResServerLoginFailed defaultInstance;
    public static ResServerLoginFailed getDefaultInstance() {
      return defaultInstance;
    }

    public ResServerLoginFailed getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResServerLoginFailed(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              description_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.luv.face2face.protobuf.generate.ser2cli.login.Server.internal_static_ResServerLoginFailed_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.luv.face2face.protobuf.generate.ser2cli.login.Server.internal_static_ResServerLoginFailed_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed.class, com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed.Builder.class);
    }

    public static com.google.protobuf.Parser<ResServerLoginFailed> PARSER =
        new com.google.protobuf.AbstractParser<ResServerLoginFailed>() {
      public ResServerLoginFailed parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResServerLoginFailed(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResServerLoginFailed> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string description = 1;
    public static final int DESCRIPTION_FIELD_NUMBER = 1;
    private java.lang.Object description_;
    /**
     * <code>required string description = 1;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string description = 1;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string description = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      description_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDescription()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDescriptionBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDescriptionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResServerLoginFailed}
     *
     * <pre>
     *服务器登录失败响应
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.luv.face2face.protobuf.generate.ser2cli.login.Server.internal_static_ResServerLoginFailed_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.luv.face2face.protobuf.generate.ser2cli.login.Server.internal_static_ResServerLoginFailed_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed.class, com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed.Builder.class);
      }

      // Construct using com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.luv.face2face.protobuf.generate.ser2cli.login.Server.internal_static_ResServerLoginFailed_descriptor;
      }

      public com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed getDefaultInstanceForType() {
        return com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed.getDefaultInstance();
      }

      public com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed build() {
        com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed buildPartial() {
        com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed result = new com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.description_ = description_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed) {
          return mergeFrom((com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed other) {
        if (other == com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed.getDefaultInstance()) return this;
        if (other.hasDescription()) {
          bitField0_ |= 0x00000001;
          description_ = other.description_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDescription()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerLoginFailed) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string description = 1;
      private java.lang.Object description_ = "";
      /**
       * <code>required string description = 1;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string description = 1;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string description = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string description = 1;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string description = 1;</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000001);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>required string description = 1;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        description_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ResServerLoginFailed)
    }

    static {
      defaultInstance = new ResServerLoginFailed(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ResServerLoginFailed)
  }

  public interface ResServerRegisterSuccOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string description = 1;
    /**
     * <code>required string description = 1;</code>
     */
    boolean hasDescription();
    /**
     * <code>required string description = 1;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>required string description = 1;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    // required int64 userId = 2;
    /**
     * <code>required int64 userId = 2;</code>
     */
    boolean hasUserId();
    /**
     * <code>required int64 userId = 2;</code>
     */
    long getUserId();
  }
  /**
   * Protobuf type {@code ResServerRegisterSucc}
   *
   * <pre>
   *服务器注册成功响应
   * </pre>
   */
  public static final class ResServerRegisterSucc extends
      com.google.protobuf.GeneratedMessage
      implements ResServerRegisterSuccOrBuilder {
    // Use ResServerRegisterSucc.newBuilder() to construct.
    private ResServerRegisterSucc(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResServerRegisterSucc(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResServerRegisterSucc defaultInstance;
    public static ResServerRegisterSucc getDefaultInstance() {
      return defaultInstance;
    }

    public ResServerRegisterSucc getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResServerRegisterSucc(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              description_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              userId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.luv.face2face.protobuf.generate.ser2cli.login.Server.internal_static_ResServerRegisterSucc_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.luv.face2face.protobuf.generate.ser2cli.login.Server.internal_static_ResServerRegisterSucc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc.class, com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc.Builder.class);
    }

    public static com.google.protobuf.Parser<ResServerRegisterSucc> PARSER =
        new com.google.protobuf.AbstractParser<ResServerRegisterSucc>() {
      public ResServerRegisterSucc parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResServerRegisterSucc(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResServerRegisterSucc> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string description = 1;
    public static final int DESCRIPTION_FIELD_NUMBER = 1;
    private java.lang.Object description_;
    /**
     * <code>required string description = 1;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string description = 1;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string description = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 userId = 2;
    public static final int USERID_FIELD_NUMBER = 2;
    private long userId_;
    /**
     * <code>required int64 userId = 2;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 userId = 2;</code>
     */
    public long getUserId() {
      return userId_;
    }

    private void initFields() {
      description_ = "";
      userId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDescription()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, userId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, userId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResServerRegisterSucc}
     *
     * <pre>
     *服务器注册成功响应
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSuccOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.luv.face2face.protobuf.generate.ser2cli.login.Server.internal_static_ResServerRegisterSucc_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.luv.face2face.protobuf.generate.ser2cli.login.Server.internal_static_ResServerRegisterSucc_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc.class, com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc.Builder.class);
      }

      // Construct using com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.luv.face2face.protobuf.generate.ser2cli.login.Server.internal_static_ResServerRegisterSucc_descriptor;
      }

      public com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc getDefaultInstanceForType() {
        return com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc.getDefaultInstance();
      }

      public com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc build() {
        com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc buildPartial() {
        com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc result = new com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userId_ = userId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc) {
          return mergeFrom((com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc other) {
        if (other == com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc.getDefaultInstance()) return this;
        if (other.hasDescription()) {
          bitField0_ |= 0x00000001;
          description_ = other.description_;
          onChanged();
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDescription()) {
          
          return false;
        }
        if (!hasUserId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterSucc) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string description = 1;
      private java.lang.Object description_ = "";
      /**
       * <code>required string description = 1;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string description = 1;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string description = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string description = 1;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string description = 1;</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000001);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>required string description = 1;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        description_ = value;
        onChanged();
        return this;
      }

      // required int64 userId = 2;
      private long userId_ ;
      /**
       * <code>required int64 userId = 2;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 userId = 2;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>required int64 userId = 2;</code>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000002;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 userId = 2;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ResServerRegisterSucc)
    }

    static {
      defaultInstance = new ResServerRegisterSucc(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ResServerRegisterSucc)
  }

  public interface ResServerRegisterFailedOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string description = 1;
    /**
     * <code>required string description = 1;</code>
     */
    boolean hasDescription();
    /**
     * <code>required string description = 1;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>required string description = 1;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code ResServerRegisterFailed}
   *
   * <pre>
   *服务器注册失败响应
   * </pre>
   */
  public static final class ResServerRegisterFailed extends
      com.google.protobuf.GeneratedMessage
      implements ResServerRegisterFailedOrBuilder {
    // Use ResServerRegisterFailed.newBuilder() to construct.
    private ResServerRegisterFailed(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResServerRegisterFailed(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResServerRegisterFailed defaultInstance;
    public static ResServerRegisterFailed getDefaultInstance() {
      return defaultInstance;
    }

    public ResServerRegisterFailed getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResServerRegisterFailed(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              description_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.luv.face2face.protobuf.generate.ser2cli.login.Server.internal_static_ResServerRegisterFailed_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.luv.face2face.protobuf.generate.ser2cli.login.Server.internal_static_ResServerRegisterFailed_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed.class, com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed.Builder.class);
    }

    public static com.google.protobuf.Parser<ResServerRegisterFailed> PARSER =
        new com.google.protobuf.AbstractParser<ResServerRegisterFailed>() {
      public ResServerRegisterFailed parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResServerRegisterFailed(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResServerRegisterFailed> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string description = 1;
    public static final int DESCRIPTION_FIELD_NUMBER = 1;
    private java.lang.Object description_;
    /**
     * <code>required string description = 1;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string description = 1;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string description = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      description_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDescription()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDescriptionBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDescriptionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResServerRegisterFailed}
     *
     * <pre>
     *服务器注册失败响应
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.luv.face2face.protobuf.generate.ser2cli.login.Server.internal_static_ResServerRegisterFailed_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.luv.face2face.protobuf.generate.ser2cli.login.Server.internal_static_ResServerRegisterFailed_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed.class, com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed.Builder.class);
      }

      // Construct using com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.luv.face2face.protobuf.generate.ser2cli.login.Server.internal_static_ResServerRegisterFailed_descriptor;
      }

      public com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed getDefaultInstanceForType() {
        return com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed.getDefaultInstance();
      }

      public com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed build() {
        com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed buildPartial() {
        com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed result = new com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.description_ = description_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed) {
          return mergeFrom((com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed other) {
        if (other == com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed.getDefaultInstance()) return this;
        if (other.hasDescription()) {
          bitField0_ |= 0x00000001;
          description_ = other.description_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDescription()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.luv.face2face.protobuf.generate.ser2cli.login.Server.ResServerRegisterFailed) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string description = 1;
      private java.lang.Object description_ = "";
      /**
       * <code>required string description = 1;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string description = 1;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string description = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string description = 1;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string description = 1;</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000001);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>required string description = 1;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        description_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ResServerRegisterFailed)
    }

    static {
      defaultInstance = new ResServerRegisterFailed(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ResServerRegisterFailed)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ResServerLoginSucc_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResServerLoginSucc_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ResServerLoginFailed_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResServerLoginFailed_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ResServerRegisterSucc_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResServerRegisterSucc_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ResServerRegisterFailed_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResServerRegisterFailed_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026server_def/login.proto\")\n\022ResServerLog" +
      "inSucc\022\023\n\013description\030\001 \002(\t\"+\n\024ResServer" +
      "LoginFailed\022\023\n\013description\030\001 \002(\t\"<\n\025ResS" +
      "erverRegisterSucc\022\023\n\013description\030\001 \002(\t\022\016" +
      "\n\006userId\030\002 \002(\003\".\n\027ResServerRegisterFaile" +
      "d\022\023\n\013description\030\001 \002(\tB;\n1com.luv.face2f" +
      "ace.protobuf.generate.ser2cli.loginB\006Ser" +
      "ver"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ResServerLoginSucc_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ResServerLoginSucc_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ResServerLoginSucc_descriptor,
              new java.lang.String[] { "Description", });
          internal_static_ResServerLoginFailed_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ResServerLoginFailed_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ResServerLoginFailed_descriptor,
              new java.lang.String[] { "Description", });
          internal_static_ResServerRegisterSucc_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_ResServerRegisterSucc_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ResServerRegisterSucc_descriptor,
              new java.lang.String[] { "Description", "UserId", });
          internal_static_ResServerRegisterFailed_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_ResServerRegisterFailed_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ResServerRegisterFailed_descriptor,
              new java.lang.String[] { "Description", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
