// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_def/file.proto

package com.luv.face2face.protobuf.generate.ser2cli.file;

public final class Server {
  private Server() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReqFileUploadMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 formUserId = 1;
    /**
     * <code>required int64 formUserId = 1;</code>
     *
     * <pre>
     *源用户
     * </pre>
     */
    boolean hasFormUserId();
    /**
     * <code>required int64 formUserId = 1;</code>
     *
     * <pre>
     *源用户
     * </pre>
     */
    long getFormUserId();

    // required int64 toUserId = 2;
    /**
     * <code>required int64 toUserId = 2;</code>
     *
     * <pre>
     *目的用户
     * </pre>
     */
    boolean hasToUserId();
    /**
     * <code>required int64 toUserId = 2;</code>
     *
     * <pre>
     *目的用户
     * </pre>
     */
    long getToUserId();

    // required int64 fileLength = 3;
    /**
     * <code>required int64 fileLength = 3;</code>
     *
     * <pre>
     *文件长度
     * </pre>
     */
    boolean hasFileLength();
    /**
     * <code>required int64 fileLength = 3;</code>
     *
     * <pre>
     *文件长度
     * </pre>
     */
    long getFileLength();

    // required string fileName = 5;
    /**
     * <code>required string fileName = 5;</code>
     *
     * <pre>
     *文件名
     * </pre>
     */
    boolean hasFileName();
    /**
     * <code>required string fileName = 5;</code>
     *
     * <pre>
     *文件名
     * </pre>
     */
    java.lang.String getFileName();
    /**
     * <code>required string fileName = 5;</code>
     *
     * <pre>
     *文件名
     * </pre>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    // required string fileType = 6;
    /**
     * <code>required string fileType = 6;</code>
     *
     * <pre>
     *文件类型
     * </pre>
     */
    boolean hasFileType();
    /**
     * <code>required string fileType = 6;</code>
     *
     * <pre>
     *文件类型
     * </pre>
     */
    java.lang.String getFileType();
    /**
     * <code>required string fileType = 6;</code>
     *
     * <pre>
     *文件类型
     * </pre>
     */
    com.google.protobuf.ByteString
        getFileTypeBytes();

    // required string localPath = 7;
    /**
     * <code>required string localPath = 7;</code>
     *
     * <pre>
     *本地的文件上传路径
     * </pre>
     */
    boolean hasLocalPath();
    /**
     * <code>required string localPath = 7;</code>
     *
     * <pre>
     *本地的文件上传路径
     * </pre>
     */
    java.lang.String getLocalPath();
    /**
     * <code>required string localPath = 7;</code>
     *
     * <pre>
     *本地的文件上传路径
     * </pre>
     */
    com.google.protobuf.ByteString
        getLocalPathBytes();
  }
  /**
   * Protobuf type {@code ReqFileUploadMsg}
   *
   * <pre>
   *文件上传请求包
   * </pre>
   */
  public static final class ReqFileUploadMsg extends
      com.google.protobuf.GeneratedMessage
      implements ReqFileUploadMsgOrBuilder {
    // Use ReqFileUploadMsg.newBuilder() to construct.
    private ReqFileUploadMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqFileUploadMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqFileUploadMsg defaultInstance;
    public static ReqFileUploadMsg getDefaultInstance() {
      return defaultInstance;
    }

    public ReqFileUploadMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqFileUploadMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              formUserId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              toUserId_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              fileLength_ = input.readInt64();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000008;
              fileName_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000010;
              fileType_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000020;
              localPath_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.luv.face2face.protobuf.generate.ser2cli.file.Server.internal_static_ReqFileUploadMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.luv.face2face.protobuf.generate.ser2cli.file.Server.internal_static_ReqFileUploadMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg.class, com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqFileUploadMsg> PARSER =
        new com.google.protobuf.AbstractParser<ReqFileUploadMsg>() {
      public ReqFileUploadMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqFileUploadMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqFileUploadMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 formUserId = 1;
    public static final int FORMUSERID_FIELD_NUMBER = 1;
    private long formUserId_;
    /**
     * <code>required int64 formUserId = 1;</code>
     *
     * <pre>
     *源用户
     * </pre>
     */
    public boolean hasFormUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 formUserId = 1;</code>
     *
     * <pre>
     *源用户
     * </pre>
     */
    public long getFormUserId() {
      return formUserId_;
    }

    // required int64 toUserId = 2;
    public static final int TOUSERID_FIELD_NUMBER = 2;
    private long toUserId_;
    /**
     * <code>required int64 toUserId = 2;</code>
     *
     * <pre>
     *目的用户
     * </pre>
     */
    public boolean hasToUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 toUserId = 2;</code>
     *
     * <pre>
     *目的用户
     * </pre>
     */
    public long getToUserId() {
      return toUserId_;
    }

    // required int64 fileLength = 3;
    public static final int FILELENGTH_FIELD_NUMBER = 3;
    private long fileLength_;
    /**
     * <code>required int64 fileLength = 3;</code>
     *
     * <pre>
     *文件长度
     * </pre>
     */
    public boolean hasFileLength() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 fileLength = 3;</code>
     *
     * <pre>
     *文件长度
     * </pre>
     */
    public long getFileLength() {
      return fileLength_;
    }

    // required string fileName = 5;
    public static final int FILENAME_FIELD_NUMBER = 5;
    private java.lang.Object fileName_;
    /**
     * <code>required string fileName = 5;</code>
     *
     * <pre>
     *文件名
     * </pre>
     */
    public boolean hasFileName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string fileName = 5;</code>
     *
     * <pre>
     *文件名
     * </pre>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fileName = 5;</code>
     *
     * <pre>
     *文件名
     * </pre>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string fileType = 6;
    public static final int FILETYPE_FIELD_NUMBER = 6;
    private java.lang.Object fileType_;
    /**
     * <code>required string fileType = 6;</code>
     *
     * <pre>
     *文件类型
     * </pre>
     */
    public boolean hasFileType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string fileType = 6;</code>
     *
     * <pre>
     *文件类型
     * </pre>
     */
    public java.lang.String getFileType() {
      java.lang.Object ref = fileType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fileType = 6;</code>
     *
     * <pre>
     *文件类型
     * </pre>
     */
    public com.google.protobuf.ByteString
        getFileTypeBytes() {
      java.lang.Object ref = fileType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string localPath = 7;
    public static final int LOCALPATH_FIELD_NUMBER = 7;
    private java.lang.Object localPath_;
    /**
     * <code>required string localPath = 7;</code>
     *
     * <pre>
     *本地的文件上传路径
     * </pre>
     */
    public boolean hasLocalPath() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string localPath = 7;</code>
     *
     * <pre>
     *本地的文件上传路径
     * </pre>
     */
    public java.lang.String getLocalPath() {
      java.lang.Object ref = localPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          localPath_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string localPath = 7;</code>
     *
     * <pre>
     *本地的文件上传路径
     * </pre>
     */
    public com.google.protobuf.ByteString
        getLocalPathBytes() {
      java.lang.Object ref = localPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      formUserId_ = 0L;
      toUserId_ = 0L;
      fileLength_ = 0L;
      fileName_ = "";
      fileType_ = "";
      localPath_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFormUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFileLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFileName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFileType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocalPath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, formUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, toUserId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, fileLength_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getFileTypeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(7, getLocalPathBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, formUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, toUserId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, fileLength_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getFileTypeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getLocalPathBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReqFileUploadMsg}
     *
     * <pre>
     *文件上传请求包
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.luv.face2face.protobuf.generate.ser2cli.file.Server.internal_static_ReqFileUploadMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.luv.face2face.protobuf.generate.ser2cli.file.Server.internal_static_ReqFileUploadMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg.class, com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg.Builder.class);
      }

      // Construct using com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        formUserId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        toUserId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        fileLength_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        fileName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        fileType_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        localPath_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.luv.face2face.protobuf.generate.ser2cli.file.Server.internal_static_ReqFileUploadMsg_descriptor;
      }

      public com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg getDefaultInstanceForType() {
        return com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg.getDefaultInstance();
      }

      public com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg build() {
        com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg buildPartial() {
        com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg result = new com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.formUserId_ = formUserId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.toUserId_ = toUserId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fileLength_ = fileLength_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.fileName_ = fileName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.fileType_ = fileType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.localPath_ = localPath_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg) {
          return mergeFrom((com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg other) {
        if (other == com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg.getDefaultInstance()) return this;
        if (other.hasFormUserId()) {
          setFormUserId(other.getFormUserId());
        }
        if (other.hasToUserId()) {
          setToUserId(other.getToUserId());
        }
        if (other.hasFileLength()) {
          setFileLength(other.getFileLength());
        }
        if (other.hasFileName()) {
          bitField0_ |= 0x00000008;
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.hasFileType()) {
          bitField0_ |= 0x00000010;
          fileType_ = other.fileType_;
          onChanged();
        }
        if (other.hasLocalPath()) {
          bitField0_ |= 0x00000020;
          localPath_ = other.localPath_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFormUserId()) {
          
          return false;
        }
        if (!hasToUserId()) {
          
          return false;
        }
        if (!hasFileLength()) {
          
          return false;
        }
        if (!hasFileName()) {
          
          return false;
        }
        if (!hasFileType()) {
          
          return false;
        }
        if (!hasLocalPath()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.luv.face2face.protobuf.generate.ser2cli.file.Server.ReqFileUploadMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 formUserId = 1;
      private long formUserId_ ;
      /**
       * <code>required int64 formUserId = 1;</code>
       *
       * <pre>
       *源用户
       * </pre>
       */
      public boolean hasFormUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 formUserId = 1;</code>
       *
       * <pre>
       *源用户
       * </pre>
       */
      public long getFormUserId() {
        return formUserId_;
      }
      /**
       * <code>required int64 formUserId = 1;</code>
       *
       * <pre>
       *源用户
       * </pre>
       */
      public Builder setFormUserId(long value) {
        bitField0_ |= 0x00000001;
        formUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 formUserId = 1;</code>
       *
       * <pre>
       *源用户
       * </pre>
       */
      public Builder clearFormUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        formUserId_ = 0L;
        onChanged();
        return this;
      }

      // required int64 toUserId = 2;
      private long toUserId_ ;
      /**
       * <code>required int64 toUserId = 2;</code>
       *
       * <pre>
       *目的用户
       * </pre>
       */
      public boolean hasToUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 toUserId = 2;</code>
       *
       * <pre>
       *目的用户
       * </pre>
       */
      public long getToUserId() {
        return toUserId_;
      }
      /**
       * <code>required int64 toUserId = 2;</code>
       *
       * <pre>
       *目的用户
       * </pre>
       */
      public Builder setToUserId(long value) {
        bitField0_ |= 0x00000002;
        toUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 toUserId = 2;</code>
       *
       * <pre>
       *目的用户
       * </pre>
       */
      public Builder clearToUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        toUserId_ = 0L;
        onChanged();
        return this;
      }

      // required int64 fileLength = 3;
      private long fileLength_ ;
      /**
       * <code>required int64 fileLength = 3;</code>
       *
       * <pre>
       *文件长度
       * </pre>
       */
      public boolean hasFileLength() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 fileLength = 3;</code>
       *
       * <pre>
       *文件长度
       * </pre>
       */
      public long getFileLength() {
        return fileLength_;
      }
      /**
       * <code>required int64 fileLength = 3;</code>
       *
       * <pre>
       *文件长度
       * </pre>
       */
      public Builder setFileLength(long value) {
        bitField0_ |= 0x00000004;
        fileLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 fileLength = 3;</code>
       *
       * <pre>
       *文件长度
       * </pre>
       */
      public Builder clearFileLength() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fileLength_ = 0L;
        onChanged();
        return this;
      }

      // required string fileName = 5;
      private java.lang.Object fileName_ = "";
      /**
       * <code>required string fileName = 5;</code>
       *
       * <pre>
       *文件名
       * </pre>
       */
      public boolean hasFileName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string fileName = 5;</code>
       *
       * <pre>
       *文件名
       * </pre>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fileName = 5;</code>
       *
       * <pre>
       *文件名
       * </pre>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fileName = 5;</code>
       *
       * <pre>
       *文件名
       * </pre>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fileName = 5;</code>
       *
       * <pre>
       *文件名
       * </pre>
       */
      public Builder clearFileName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>required string fileName = 5;</code>
       *
       * <pre>
       *文件名
       * </pre>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        fileName_ = value;
        onChanged();
        return this;
      }

      // required string fileType = 6;
      private java.lang.Object fileType_ = "";
      /**
       * <code>required string fileType = 6;</code>
       *
       * <pre>
       *文件类型
       * </pre>
       */
      public boolean hasFileType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string fileType = 6;</code>
       *
       * <pre>
       *文件类型
       * </pre>
       */
      public java.lang.String getFileType() {
        java.lang.Object ref = fileType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fileType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fileType = 6;</code>
       *
       * <pre>
       *文件类型
       * </pre>
       */
      public com.google.protobuf.ByteString
          getFileTypeBytes() {
        java.lang.Object ref = fileType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fileType = 6;</code>
       *
       * <pre>
       *文件类型
       * </pre>
       */
      public Builder setFileType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        fileType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fileType = 6;</code>
       *
       * <pre>
       *文件类型
       * </pre>
       */
      public Builder clearFileType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        fileType_ = getDefaultInstance().getFileType();
        onChanged();
        return this;
      }
      /**
       * <code>required string fileType = 6;</code>
       *
       * <pre>
       *文件类型
       * </pre>
       */
      public Builder setFileTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        fileType_ = value;
        onChanged();
        return this;
      }

      // required string localPath = 7;
      private java.lang.Object localPath_ = "";
      /**
       * <code>required string localPath = 7;</code>
       *
       * <pre>
       *本地的文件上传路径
       * </pre>
       */
      public boolean hasLocalPath() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string localPath = 7;</code>
       *
       * <pre>
       *本地的文件上传路径
       * </pre>
       */
      public java.lang.String getLocalPath() {
        java.lang.Object ref = localPath_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          localPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string localPath = 7;</code>
       *
       * <pre>
       *本地的文件上传路径
       * </pre>
       */
      public com.google.protobuf.ByteString
          getLocalPathBytes() {
        java.lang.Object ref = localPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string localPath = 7;</code>
       *
       * <pre>
       *本地的文件上传路径
       * </pre>
       */
      public Builder setLocalPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        localPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string localPath = 7;</code>
       *
       * <pre>
       *本地的文件上传路径
       * </pre>
       */
      public Builder clearLocalPath() {
        bitField0_ = (bitField0_ & ~0x00000020);
        localPath_ = getDefaultInstance().getLocalPath();
        onChanged();
        return this;
      }
      /**
       * <code>required string localPath = 7;</code>
       *
       * <pre>
       *本地的文件上传路径
       * </pre>
       */
      public Builder setLocalPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        localPath_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ReqFileUploadMsg)
    }

    static {
      defaultInstance = new ReqFileUploadMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ReqFileUploadMsg)
  }

  public interface ResFileUploadPromiseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string promise = 1;
    /**
     * <code>required string promise = 1;</code>
     */
    boolean hasPromise();
    /**
     * <code>required string promise = 1;</code>
     */
    java.lang.String getPromise();
    /**
     * <code>required string promise = 1;</code>
     */
    com.google.protobuf.ByteString
        getPromiseBytes();

    // required string yourFilePath = 2;
    /**
     * <code>required string yourFilePath = 2;</code>
     */
    boolean hasYourFilePath();
    /**
     * <code>required string yourFilePath = 2;</code>
     */
    java.lang.String getYourFilePath();
    /**
     * <code>required string yourFilePath = 2;</code>
     */
    com.google.protobuf.ByteString
        getYourFilePathBytes();

    // required string description = 3;
    /**
     * <code>required string description = 3;</code>
     */
    boolean hasDescription();
    /**
     * <code>required string description = 3;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>required string description = 3;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code ResFileUploadPromise}
   *
   * <pre>
   *文件上传准许
   * </pre>
   */
  public static final class ResFileUploadPromise extends
      com.google.protobuf.GeneratedMessage
      implements ResFileUploadPromiseOrBuilder {
    // Use ResFileUploadPromise.newBuilder() to construct.
    private ResFileUploadPromise(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResFileUploadPromise(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResFileUploadPromise defaultInstance;
    public static ResFileUploadPromise getDefaultInstance() {
      return defaultInstance;
    }

    public ResFileUploadPromise getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResFileUploadPromise(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              promise_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              yourFilePath_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              description_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.luv.face2face.protobuf.generate.ser2cli.file.Server.internal_static_ResFileUploadPromise_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.luv.face2face.protobuf.generate.ser2cli.file.Server.internal_static_ResFileUploadPromise_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise.class, com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise.Builder.class);
    }

    public static com.google.protobuf.Parser<ResFileUploadPromise> PARSER =
        new com.google.protobuf.AbstractParser<ResFileUploadPromise>() {
      public ResFileUploadPromise parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResFileUploadPromise(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResFileUploadPromise> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string promise = 1;
    public static final int PROMISE_FIELD_NUMBER = 1;
    private java.lang.Object promise_;
    /**
     * <code>required string promise = 1;</code>
     */
    public boolean hasPromise() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string promise = 1;</code>
     */
    public java.lang.String getPromise() {
      java.lang.Object ref = promise_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          promise_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string promise = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPromiseBytes() {
      java.lang.Object ref = promise_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        promise_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string yourFilePath = 2;
    public static final int YOURFILEPATH_FIELD_NUMBER = 2;
    private java.lang.Object yourFilePath_;
    /**
     * <code>required string yourFilePath = 2;</code>
     */
    public boolean hasYourFilePath() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string yourFilePath = 2;</code>
     */
    public java.lang.String getYourFilePath() {
      java.lang.Object ref = yourFilePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          yourFilePath_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string yourFilePath = 2;</code>
     */
    public com.google.protobuf.ByteString
        getYourFilePathBytes() {
      java.lang.Object ref = yourFilePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        yourFilePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string description = 3;
    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private java.lang.Object description_;
    /**
     * <code>required string description = 3;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string description = 3;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string description = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      promise_ = "";
      yourFilePath_ = "";
      description_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPromise()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasYourFilePath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDescription()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPromiseBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getYourFilePathBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDescriptionBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPromiseBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getYourFilePathBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescriptionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResFileUploadPromise}
     *
     * <pre>
     *文件上传准许
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromiseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.luv.face2face.protobuf.generate.ser2cli.file.Server.internal_static_ResFileUploadPromise_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.luv.face2face.protobuf.generate.ser2cli.file.Server.internal_static_ResFileUploadPromise_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise.class, com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise.Builder.class);
      }

      // Construct using com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        promise_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        yourFilePath_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.luv.face2face.protobuf.generate.ser2cli.file.Server.internal_static_ResFileUploadPromise_descriptor;
      }

      public com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise getDefaultInstanceForType() {
        return com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise.getDefaultInstance();
      }

      public com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise build() {
        com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise buildPartial() {
        com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise result = new com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.promise_ = promise_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.yourFilePath_ = yourFilePath_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.description_ = description_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise) {
          return mergeFrom((com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise other) {
        if (other == com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise.getDefaultInstance()) return this;
        if (other.hasPromise()) {
          bitField0_ |= 0x00000001;
          promise_ = other.promise_;
          onChanged();
        }
        if (other.hasYourFilePath()) {
          bitField0_ |= 0x00000002;
          yourFilePath_ = other.yourFilePath_;
          onChanged();
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000004;
          description_ = other.description_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPromise()) {
          
          return false;
        }
        if (!hasYourFilePath()) {
          
          return false;
        }
        if (!hasDescription()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.luv.face2face.protobuf.generate.ser2cli.file.Server.ResFileUploadPromise) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string promise = 1;
      private java.lang.Object promise_ = "";
      /**
       * <code>required string promise = 1;</code>
       */
      public boolean hasPromise() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string promise = 1;</code>
       */
      public java.lang.String getPromise() {
        java.lang.Object ref = promise_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          promise_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string promise = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPromiseBytes() {
        java.lang.Object ref = promise_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          promise_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string promise = 1;</code>
       */
      public Builder setPromise(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        promise_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string promise = 1;</code>
       */
      public Builder clearPromise() {
        bitField0_ = (bitField0_ & ~0x00000001);
        promise_ = getDefaultInstance().getPromise();
        onChanged();
        return this;
      }
      /**
       * <code>required string promise = 1;</code>
       */
      public Builder setPromiseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        promise_ = value;
        onChanged();
        return this;
      }

      // required string yourFilePath = 2;
      private java.lang.Object yourFilePath_ = "";
      /**
       * <code>required string yourFilePath = 2;</code>
       */
      public boolean hasYourFilePath() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string yourFilePath = 2;</code>
       */
      public java.lang.String getYourFilePath() {
        java.lang.Object ref = yourFilePath_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          yourFilePath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string yourFilePath = 2;</code>
       */
      public com.google.protobuf.ByteString
          getYourFilePathBytes() {
        java.lang.Object ref = yourFilePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          yourFilePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string yourFilePath = 2;</code>
       */
      public Builder setYourFilePath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        yourFilePath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string yourFilePath = 2;</code>
       */
      public Builder clearYourFilePath() {
        bitField0_ = (bitField0_ & ~0x00000002);
        yourFilePath_ = getDefaultInstance().getYourFilePath();
        onChanged();
        return this;
      }
      /**
       * <code>required string yourFilePath = 2;</code>
       */
      public Builder setYourFilePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        yourFilePath_ = value;
        onChanged();
        return this;
      }

      // required string description = 3;
      private java.lang.Object description_ = "";
      /**
       * <code>required string description = 3;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string description = 3;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string description = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string description = 3;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string description = 3;</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>required string description = 3;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ResFileUploadPromise)
    }

    static {
      defaultInstance = new ResFileUploadPromise(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ResFileUploadPromise)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqFileUploadMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReqFileUploadMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ResFileUploadPromise_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResFileUploadPromise_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025server_def/file.proto\"\203\001\n\020ReqFileUploa" +
      "dMsg\022\022\n\nformUserId\030\001 \002(\003\022\020\n\010toUserId\030\002 \002" +
      "(\003\022\022\n\nfileLength\030\003 \002(\003\022\020\n\010fileName\030\005 \002(\t" +
      "\022\020\n\010fileType\030\006 \002(\t\022\021\n\tlocalPath\030\007 \002(\t\"R\n" +
      "\024ResFileUploadPromise\022\017\n\007promise\030\001 \002(\t\022\024" +
      "\n\014yourFilePath\030\002 \002(\t\022\023\n\013description\030\003 \002(" +
      "\tB:\n0com.luv.face2face.protobuf.generate" +
      ".ser2cli.fileB\006Server"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ReqFileUploadMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ReqFileUploadMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ReqFileUploadMsg_descriptor,
              new java.lang.String[] { "FormUserId", "ToUserId", "FileLength", "FileName", "FileType", "LocalPath", });
          internal_static_ResFileUploadPromise_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ResFileUploadPromise_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ResFileUploadPromise_descriptor,
              new java.lang.String[] { "Promise", "YourFilePath", "Description", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
